# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
    - 'Status: Triage'
    - 'Status: Confirmed'
    - 'Status: ToDo'
    - 'Status: Blocked'
    - 'Status: Returned'
    - 'Status: In Progress'
    - 'Status: Blocking'
    - 'Status: For Review'
    - 'Status: Under Review'
    - 'Status: To Merge'
    - "Status: Can't Replicate"
    - 'Status: Duplicate'
    - "Status: Won't Fix"
    - 'Status: DONE'
# Label to use when marking an issue as stale
staleLabel: '💤 STALE'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
