blank_issues_enabled: false
contact_links:
    - name: RedEyed SubStack
      url: https://redeyed.substack.com
      about: The RedEyed SubStack is our primary community hub where you will find Newsletters & Blogs

    - name: RedEyed-RPG @ Facebook
      url: https://facebook.com/RedEyedRPG
      about: Follow us on Facebook

    - name: PATREON | Ragdata
      url: https://patreon.com/ragdata
      about: Support me at Patreon

    - name: Sponsor me @ Github
      url: https://github.com/sponsors/ragdata
      about: Sponsor one of my projects
