####################################################################
# jekyll-ghpages-tagging.reuse.yml
####################################################################
# This file is provided as an example of how to call the
# jekyll-ghpages-tagging reusable workflow.
#
# File:         jekyll-ghpages-tagging.reuse.yml
# Version:      1.0
# Author:       Ragdata
# Date:         08/07/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Darren (Ragdata) Poulton
####################################################################
name: Jekyll GH-Pages Tagging - Reusable

on:
    # Allows this workflow to be called by other workflows
    workflow_call:
        inputs:
            posts_dir:
                description: "Path to '_posts' directory from root"
                required: false
                type: string
                default: "_posts"
            tags_dir:
                description: "Path to '_tags' directory from root"
                required: false
                type: string
                default: "_tags"
            tags_layout:
                description: "Layout used by tag files"
                required: false
                type: string
                default: "tags"
            feeds_dir:
                description: "Path to '_feeds' directory from root"
                required: false
                type: string
                default: "_feeds"
            feeds_layout:
                description: "Layout used by feed files"
                required: false
                type: string
                default: "feed"
            prune_tags:
                description: "Remove unused tags"
                required: false
                type: boolean
                default: true
        secrets:
            token:
                required: true

jobs:

    generate_tags:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate Tags
              uses: ragdata/jekyll-ghpages-tagging@master
              with:
                  posts_dir: ${{ inputs.posts_dir }}
                  tags_dir: ${{ inputs.tags_dir }}
                  tags_layout: ${{ inputs.tags_layout }}
                  feeds_dir: ${{ inputs.feeds_dir }}
                  feeds_layout: ${{ inputs.feeds_layout }}
                  prune_tags: ${{ inputs.prune_tags }}
              env:
                  GITHUB_TOKEN: ${{ secrets.token }}
