####################################################################
# jekyll-ghpages-tagging.flow.yml
####################################################################
# Jekyll GH-Pages Tagging Workflow
#
# File:         jekyll-ghpages-tagging.flow.yml
# Version:      1.0
# Author:       Ragdata
# Date:         08/07/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Darren (Ragdata) Poulton
####################################################################
name: Jekyll GH-Pages Tagging

on:
    # Trigger whenever .md files in the _posts directory on the master branch are pushed
    push:
        branches:
            - $default-branch
        paths:
            - "_posts/*.md"
    # Allows for manual triggering via Actions tab
    workflow_dispatch:

jobs:

    generate_tags:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate Tags
              uses: ragdata/jekyll-ghpages-tagging@master
              with:
                  posts_dir: "_posts"
                  tags_dir: "_tags"
                  tags_layout: "tags"
                  feeds_dir: "_feeds"
                  feeds_layout: "feed"
                  prune_tags: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
