name: Ragdata's Community Health Files Repository
description: Everything you need to build a healthy GitHub Repository and Open Source Community
version: 0.1.0
copyright: Copyright © 2024 Redeyed Technologies
website: https://github.com/ragdata/.github
repo_label: Reusable Workflows
repo_url: https://github.com/ragdata/.github
authors:
    - username: Ragdata
      first_name: Darren
      surname: Poulton
      email: ragdata@ragdata.dev
      affiliation: Redeyed Technologies
changelog: true
release: true
logged:
    - feat
    - fix
    - perf
    - style
    - docs
    - ci
